DROP TABLE RENT;
DROP TABLE NOTICE;
DROP TABLE BOOK;
DROP TABLE MEMBER;

DROP TABLE MEMBER_GRADE;
DROP TABLE BOOK_STATUS;
DROP TABLE BOOK_CATEGORY;
DROP TABLE NOTICE_CATEGORY;
DROP TABLE BOOK_IMAGE;

CREATE TABLE MEMBER(
	NO NUMBER NOT NULL,
	GRADE_CODE NUMBER(2) NOT NULL,
	EMAIL VARCHAR2(80) UNIQUE NOT NULL,
	PASSWORD VARCHAR2(300) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	PHONE VARCHAR2(11) UNIQUE NOT NULL,
	ADDRESS VARCHAR2(300) NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
	MODIFIED_DATE DATE DEFAULT SYSDATE NOT NULL,
	DEL_FLAG VARCHAR2(1) DEFAULT 'N' NOT NULL
);

CREATE TABLE MEMBER_GRADE(
	CODE NUMBER(2) NOT NULL,
	NAME VARCHAR2(10) NOT NULL
);

CREATE TABLE BOOK(
	NO NUMBER NOT NULL,
	STATUS_CODE	NUMBER(2) NOT NULL,
	CATEGORY_CODE VARCHAR2(3) NOT NULL,
	IMAGE_NO NUMBER DEFAULT 0 NOT NULL,
	NAME VARCHAR2(300) NOT NULL,
	PUBLISH VARCHAR2(100) NOT NULL,
	PUBLISH_DATE DATE NOT NULL,
	WRITER VARCHAR2(300) NOT NULL,
	DEL_FLAG VARCHAR2(1) DEFAULT 'N' NOT NULL
);

CREATE TABLE BOOK_STATUS (
	CODE NUMBER(2) NOT NULL,
	NAME VARCHAR2(10) NOT NULL
);

CREATE TABLE RENT (
	NO NUMBER NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	BOOK_NO	NUMBER NOT NULL,
	RESERVE_DATE DATE NULL,
	RENT_DATE DATE NULL,
	EXPIRE_DATE DATE NULL,
	RETURN_DATE DATE NULL,
	RENT_STATUS VARCHAR2(20) DEFAULT '예약' NOT NULL,
	RETURN_SEND_FLAG VARCHAR2(1) DEFAULT 'N' NOT NULL,
	OVERDUE_SEND_FLAG VARCHAR2(1) DEFAULT 'N' NOT NULL,
	DEL_FLAG VARCHAR2(1) DEFAULT 'N' NOT NULL
);

CREATE TABLE NOTICE (
	NO NUMBER NOT NULL,
	MEMBER_NO NUMBER(10) NOT NULL,
	CATEGORY_CODE NUMBER(2) NOT NULL,
	TITLE VARCHAR2(150) NOT NULL,
	CONTENT VARCHAR2(4000) NULL,
	START_DATE DATE NULL,
	END_DATE DATE NULL,
	CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
	MODIFIED_DATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE BOOK_CATEGORY (
	CODE VARCHAR2(3) NOT NULL,
	DEPTH NUMBER(1) NOT NULL,
	NAME VARCHAR2(100) NULL
);

CREATE TABLE NOTICE_CATEGORY (
	CODE NUMBER(2) NOT NULL,
	NAME VARCHAR2(10) NOT NULL,
	SCHEDULE_FLAG VARCHAR2(1) DEFAULT 'N' NOT NULL
);

CREATE TABLE BOOK_IMAGE (
	NO NUMBER NOT NULL,
	ORIGINAL_FILE_NAME VARCHAR2(260) NOT NULL,
	STORED_FILE_NAME VARCHAR2(260) NOT NULL,
	FILE_SIZE NUMBER NULL,
	CREATED_DATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (NO);

ALTER TABLE MEMBER_GRADE ADD CONSTRAINT PK_MEMBER_GRADE PRIMARY KEY (CODE);

ALTER TABLE BOOK ADD CONSTRAINT PK_BOOK PRIMARY KEY (NO);

ALTER TABLE BOOK_STATUS ADD CONSTRAINT PK_BOOK_STATUS PRIMARY KEY (CODE);

ALTER TABLE RENT ADD CONSTRAINT PK_RENT PRIMARY KEY (NO);

ALTER TABLE NOTICE ADD CONSTRAINT PK_NOTICE PRIMARY KEY (NO);

ALTER TABLE BOOK_CATEGORY ADD CONSTRAINT PK_BOOK_CATEGORY PRIMARY KEY (CODE);

ALTER TABLE NOTICE_CATEGORY ADD CONSTRAINT PK_NOTICE_CATEGORY PRIMARY KEY (CODE);

ALTER TABLE BOOK_IMAGE ADD CONSTRAINT PK_BOOK_IMAGE PRIMARY KEY (NO);

ALTER TABLE MEMBER ADD CONSTRAINT FK_MEMBER_GRADE_TO_MEMBER FOREIGN KEY (GRADE_CODE)
REFERENCES MEMBER_GRADE (CODE);

ALTER TABLE BOOK ADD CONSTRAINT FK_BOOK_STATUS_TO_BOOK FOREIGN KEY (STATUS_CODE)
REFERENCES BOOK_STATUS (CODE);

ALTER TABLE BOOK ADD CONSTRAINT FK_BOOK_CATEGORY_TO_BOOK FOREIGN KEY (CATEGORY_CODE)
REFERENCES BOOK_CATEGORY (CODE);

ALTER TABLE BOOK ADD CONSTRAINT FK_BOOK_IMAGE_TO_BOOK FOREIGN KEY (IMAGE_NO)
REFERENCES BOOK_IMAGE (NO);

ALTER TABLE RENT ADD CONSTRAINT FK_MEMBER_TO_RENT FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER (NO);

ALTER TABLE RENT ADD CONSTRAINT FK_BOOK_TO_RENT FOREIGN KEY (BOOK_NO)
REFERENCES BOOK (NO);

ALTER TABLE NOTICE ADD CONSTRAINT FK_MEMBER_TO_NOTICE FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER (NO);

ALTER TABLE NOTICE ADD CONSTRAINT FK_NOTICE_CATEGORY_TO_NOTICE FOREIGN KEY (CATEGORY_CODE)
REFERENCES NOTICE_CATEGORY (CODE);

DROP SEQUENCE MEMBER_NO_SEQ;
DROP SEQUENCE BOOK_NO_SEQ;
DROP SEQUENCE RENT_NO_SEQ;
DROP SEQUENCE NOTICE_NO_SEQ;
DROP SEQUENCE BOOK_IMAGE_NO_SEQ;

CREATE SEQUENCE MEMBER_NO_SEQ;
CREATE SEQUENCE BOOK_NO_SEQ;
CREATE SEQUENCE RENT_NO_SEQ;
CREATE SEQUENCE NOTICE_NO_SEQ;
CREATE SEQUENCE BOOK_IMAGE_NO_SEQ;
