Insert into LIGHTBRARYADMIN.RENT (NO,MEMBER_NO,BOOK_NO,RESERVE_DATE,RENT_DATE,EXPIRE_DATE,RETURN_DATE,RETURN_SEND_FLAG,DEL_FLAG,OVERDUE_SEND_FLAG) values (28,142,2,null,null,null,null,'N','N','N');
Insert into LIGHTBRARYADMIN.RENT (NO,MEMBER_NO,BOOK_NO,RESERVE_DATE,RENT_DATE,EXPIRE_DATE,RETURN_DATE,RETURN_SEND_FLAG,DEL_FLAG,OVERDUE_SEND_FLAG) values (30,142,1,to_date('20/07/09','RR/MM/DD'),to_date('20/07/10','RR/MM/DD'),to_date('20/07/17','RR/MM/DD'),to_date('20/07/10','RR/MM/DD'),'N','N','N');

COMMIT;