DELETE FROM BOOK_IMAGE;
INSERT INTO BOOK_IMAGE VALUE(NO, ORIGINAL_FILE_NAME, STORED_FILE_NAME, FILE_SIZE, CREATED_DATE) VALUES('0', 'no_image.jpg', 'no_image.jpg', '56145', SYSDATE);
COMMIT;
SELECT * FROM BOOK_IMAGE;