DELETE FROM BOOK_STATUS;
INSERT INTO BOOK_STATUS VALUE(CODE, NAME) VALUES('0', '보관');
INSERT INTO BOOK_STATUS VALUE(CODE, NAME) VALUES('1', '예약');
INSERT INTO BOOK_STATUS VALUE(CODE, NAME) VALUES('2', '대출');
INSERT INTO BOOK_STATUS VALUE(CODE, NAME) VALUES('3', '연체');
INSERT INTO BOOK_STATUS VALUE(CODE, NAME) VALUES('4', '분실');
INSERT INTO BOOK_STATUS VALUE(CODE, NAME) VALUES('5', '파손');
COMMIT;
SELECT * FROM BOOK_STATUS;